from . import test_delivery_charge_integrity
from . import test_indiapost_barcode
from . import test_indiapost_contract
from . import test_indiapost_delivery_charge
from . import test_indiapost_settings
from . import test_indiapost_tariff
from . import test_wallet_recharge_integrity
from . import test_portal_manual_order
from . import test_portal_calculator
from . import test_indiapost_webhook
from . import test_indiapost_autobook
from . import test_indiapost_pickup_address
from . import test_awb_print_layout
